# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Checkmarx CxFlow Action
      # You may pin to the exact commit or the version.
        #uses: checkmarx-ts/checkmarx-cxflow-github-action@04e6403dbbfee0fd3fb076e5791202c31c54fe6b
        #uses: checkmarx-ts/checkmarx-cxflow-github-action@9.x
        uses: checkmarx-ts/checkmarx-cxflow-github-action@v1.0-9.x
        with:
        #Provide Checkmarx URL
          checkmarx_url: ${{secrets.CHECKMARX_URL}}
          # Select a Checkmarx Team
          team: /CxServer
          #Provide Checkmarx Username
          checkmarx_username: ${{secrets.CHECKMARX_USERNAME}}
          #Provide Checkmarx Password
          checkmarx_password: ${{secrets.CHECKMARX_PASSWORD}}
          # Provide Checkmarx Client Secret (API Token)
          checkmarx_client_secret: ${{secrets.CHECKMARX_CLIENT_SECRET}}
          # Select a Checkmarx Project
          project: Bodgeit-Github-Action
          # Select an Application Name used by downstream bug tracker systems
          app: Bodgeit
          # Break build based on Checkmarx findings?
          #break_build: # optional
          # Additional CLI parameters
          #params: --cx-flow.bug-tracker=GitHub --cxflow.bug-tracker-impl=GitHub --repo-name=bodgeit --namespace=abhishekd07 --branch=master
          # GitHub API Token
          github_token: ${{secrets.MY_GITHUB_TOKEN}}
          

      - name: Upload SARIF file
        uses: github/codeql-action/upload-sarif@v1
        with:
          sarif_file: ./cx.sarif 
